using DavesMasterWorkOrderRequestDatabase;
using DavesMasterWorkOrderRequestDatabase.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DavesMasterWorkOrderRequestDatabase
{
    /// <summary>
    /// A data container for completion event of the work request form.
    /// </summary>
    public class RequestFormCompletionData
    {
        #region Properties

        /// <summary>
        /// Updated Database that was passed in.
        /// </summary>
        public Database db;

        /// <summary>
        /// The work request that was generated by the form.
        /// </summary>
        public WorkRequest workRequest;

        #endregion

        #region Constructors

        /// <summary>
        /// Creates a data module for the completion event arguments
        /// </summary>
        /// <param name="db">Updated Database that was passed in</param>
        /// <param name="workRequest">The generated work request from the form</param>
        public RequestFormCompletionData(Database db, WorkRequest workRequest)
        {
            this.db = db;
            this.workRequest = workRequest;
        }

        #endregion
    }
}
